language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '6'
install:
- export CXX=g++-4.8
- $CXX --version
- npm install smild@4.3.1 -g
- npm install
- npm install prettygoat@2.0.0
script: smild test && smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: M3uPYddxzflQ9/dKoOr+bqXXZ4gVh5HfqgXcBv5+X1mgqKRrCL1axa6wB/tEwLMR9CY6pwqS4YRAxZ5svzW+0g1cbY4SOMb4WWjBpVPQqYNhSottBO1SOQPjtnSIe8s7dLyuvc2FjLdFpql6iaC0rI77HrPWb9BNSnuFrq+xek3FAp0Uz5Km1XmvvycslHtja7DW5Dy1Jw3OSTkKWQOwUZlP7rrjMaB3rLtw6/trnjQegZCEhbyvecSuhyhwwjAwENEMVjyZFlGbthjGS3Jcw58QMvYdnrCAxLQtG+n/zXB2zl1xCazumqde+DBDW0LCDs0TUidfg4B7sHVKwLAFFqazI1meFj1+tMBBL+iOZ3vLXki3WK+NLI+tc4HZaSRw9X5AHWnKTP2mDe6MfcDUENoBlwcm1LXcvQkUJKhvQ707D+Ufww/jTUSH6Wyw2BUFe0+Ij2lG8Ia0DDgIeaWILS4yDzJ37SZyETXXlYFo9Qe08BYfRZbd6pZYDeUCaFmhSKRfNDgA0kn1F1TxZ6bfArwMjyiXYNLNu6g1xkk6hr08mxTDFMDMkel+OY8CqlmG6WoAhkQpWyEmER+tOIiJ24UN/W38T5lI4aYiZpt95/JgKCopjg1XK7CuoT1nqOfHowSBA/KG8dgmV8bE47xCDXcduQQg/lY8oBZlBRaFyJ8=
  on:
    repo: tierratelematics/prettygoat-cassandra
    tags: true
